project:
  type: website

website:
  title: "Drone-Willow-Bumblebee"
  description: "A website for the Drone Willow Bumblebee project"
  favicon: "media/drone-bumblebee.png"

  navbar:
    logo: "media/drone-bumblebee-noleaf.png"
    left:
      - href: themes.qmd
        text: Topics
      - href: gallery.qmd
        text: Finse field work gallery
      - href: finse-willow-report.qmd
        text: Drone Report
      - href: willow-identification.qmd
        text: Willow Guide
      - href: about.qmd
        text: About us

  
  page-footer: 
    left: |
      <div id="copyright">© 2026 Drone-Willow-Bumblebee BIO-UiB</div>
    right: |
      <div class="footer-icons">
        <a href="https://www.uib.no/en">
          <img class="logo-dark" src="./media/uib_white.png" alt="UiB Logo Dark">
          <img class="logo-light" src="./media/uib_black.png" alt="UiB Logo Light">
        </a>
        <a href="index.qmd">
          <img class="logo-dark" src="./media/drone-bumblebee.png" alt="Drone Willow Bumblebee">
          <img class="logo-light" src="./media/drone-bumblebee.png" alt="Drone Willow Bumblebee">
        </a>
        <a href="https://mohnfoundation.no/en/">
          <img class="logo-dark" src="media/trond.jpg" alt="Mohn Logo"> 
          <img class="logo-light" src="media/trond.jpg" alt="Mohn Logo">
        </a>
        <a href="https://bjerknes.uib.no/en">
          <img class="logo-dark" src="media/bjerknes_white.webp" alt="Bjerknes Logo Dark">
          <img class="logo-light" src="media/bjerknes_black.webp" alt="Bjerknes Logo Light">
        </a>
      </div>

format:
  html:
    theme:
      light: 
        - minty
        - styles.scss
      dark: 
        - superhero
        - styles.scss
        - dark-theme-style.scss
    toc: true

execute:
  freeze: auto
